const challenges = [
    "Conversor de Moedas",
    "Página de Clima",
    "Tela de Login",
    "KanBan",
    "Formulário de Cartão",
    "Componente de Upload",
    "Pricing Table",
    "Página de Contatos",
    "Date Picker",
    "Card de Personagem",
    "Widget de Transporte",
    "Galeria com Hover",
    "Carrinho de Compras",
    "Profile Settings",
    "Formulário Multi Step",
    "Player de VR",
    "Página 404",
    "Plataforma de IA",
    "Antes e depois com IA"
]